# Generated by Django 2.2 on 2020-02-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapp',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='taskapp.Tagapp'),
        ),
    ]
