# Generated by Django 2.2 on 2020-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200214_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapp',
            name='status',
            field=models.IntegerField(choices=[(2, 'В ожидании'), (1, 'В процессе'), (3, 'Законченный')], default=2, verbose_name='Status'),
        ),
    ]
