# Generated by Django 2.2 on 2020-03-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_taskapp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagapp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='taskapp',
            name='finished_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='taskapp',
            name='status',
            field=models.IntegerField(choices=[(3, 'Законченный'), (1, 'В процессе'), (2, 'В ожидании')], default=2, verbose_name='Status'),
        ),
    ]
