# Generated by Django 2.2 on 2020-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20200316_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagapp',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата тега'),
        ),
        migrations.AlterField(
            model_name='taskapp',
            name='status',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'В ожидании'), (3, 'Законченный')], default=2, verbose_name='Status'),
        ),
    ]
